apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: keep2todoist-cluster # (will still be prefixed with `k3d-`)
kubeAPI: # same as `--api-port myhost.my.domain:6445` (where the name would resolve to 127.0.0.1)
  # setting port and IP on Windows explicitly as the default k3d port does lead to kubectl not being able to connect
  hostIP: "127.0.0.1"
  hostPort: "6550"